openapi: 3.0.0
info:
  title: Bank API
  version: 1.0.0
paths:
  /account/create:
    post:
      summary: Create Account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
  /account/balance:
    get:
      summary: Check Balance
      parameters:
        - in: query
          name: accountNumber
          schema:
            type: string
          required: true
          description: Account number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
  /credits/grant:
    post:
      summary: Grant Credit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditResponse'
  /credits/debt/{creditId}:
    get:
      summary: Check Credit Debt
      parameters:
        - in: path
          name: creditId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditDebtResponse'
  /credit-cards/request:
    post:
      summary: Request Credit Card
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditCardRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCardResponse'
  /credit-cards/{creditCardId}:
    get:
      summary: Check Credit Card Debt
      parameters:
        - in: path
          name: creditCardId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCardDebtResponse'
  /customers/register:
    post:
      summary: Register Customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
  /customers/search:
    get:
      summary: Get Customer by Document Number
      parameters:
        - in: query
          name: documentNumber
          schema:
            type: string
          required: true
          description: Document number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
  /transactions/deposit:
    post:
      summary: Make Deposit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
  /transactions/withdraw:
    post:
      summary: Make Withdrawal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
  /transactions/pay-installment:
    post:
      summary: Pay Installment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
  /transactions/{accountId}:
    get:
      summary: Check Transactions
      parameters:
        - in: path
          name: accountId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
  /transactions/charge:
    post:
      summary: Charge Consumption
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
components:
  schemas:
    AccountRequest:
      type: object
      properties:
        customerId:
          type: array
          items:
            type: string
        authorizedSignatory:
          type: array
          items:
            $ref: '#/components/schemas/AuthorizedSignatoryRequest'
        accountType:
          type: string
          description: Account type
    AuthorizedSignatoryRequest:
      type: object
      properties:
        name:
          type: string
        address:
          type: string
        phoneNumber:
          type: string
        documentType:
          type: string
        documentNumber:
          type: string
    AccountResponse:
      type: object
      properties:
        accountNumber:
          type: string
        monthlyTransactionLimit:
          type: integer
        maintenanceCommission:
          type: number
          format: double
        withdrawalDepositDate:
          type: string
          format: date-time
        createDate:
          type: string
          format: date-time
    BalanceResponse:
      type: object
      properties:
        accountNumber:
          type: string
        amount:
          type: number
          format: double
    CreditRequest:
      type: object
      properties:
        customerId:
          type: string
        amount:
          type: number
          format: double
        accountNumber:
          type: string
        annualInterestRate:
          type: number
          format: double
        numberOfInstallments:
          type: integer
        paymentDay:
          type: integer
        annualLateInterestRate:
          type: number
          format: double
    CreditResponse:
      type: object
      properties:
        creditId:
          type: string
        amount:
          type: number
          format: double
        annualInterestRate:
          type: number
          format: double
        numberOfInstallments:
          type: integer
        installmentAmount:
          type: number
          format: double
        paymentDay:
          type: integer
        createDate:
          type: string
          format: date-time
        annualLateInterestRate:
          type: number
          format: double
    CreditDebtResponse:
      type: object
      properties:
        creditId:
          type: string
        availableAmount:
          type: number
          format: double
        totalDebt:
          type: number
          format: double
        share:
          type: number
          format: double
    CreditCardRequest:
      type: object
      properties:
        customerId:
          type: string
        availableCredit:
          type: number
          format: double
        annualInterestRate:
          type: number
          format: double
        paymentDay:
          type: integer
        annualLateInterestRate:
          type: number
          format: double
    CreditCardResponse:
      type: object
      properties:
        creditCardNumber:
          type: string
        availableCredit:
          type: number
          format: double
        annualInterestRate:
          type: number
          format: double
        paymentDay:
          type: integer
        createDate:
          type: string
          format: date
    CreditCardDebtResponse:
      type: object
      properties:
        creditCardNumber:
          type: string
        totalDebt:
          type: number
          format: double
        share:
          type: number
          format: double
        availableCredit:
          type: number
          format: double
    CustomerRequest:
      type: object
      properties:
        fullName:
          type: string
        companyName:
          type: string
        email:
          type: string
        address:
          type: string
        phoneNumber:
          type: string
        documentType:
          type: string
        documentNumber:
          type: string
        personType:
          type: string
    CustomerResponse:
      type: object
      properties:
        customeId:
          type: string
        fullName:
          type: string
        companyName:
          type: string
        email:
          type: string
        address:
          type: string
    phoneNumber:
          type: string
    TransactionRequest:
      type: object
      properties:
        accountNumber:
          type: string
        creditCardNumber:
          type: string
        creditId:
          type: string
        amount:
          type: number
          format: double
    TransactionResponse:
      type: object
      properties:
        transactionId:
          type: integer
        accountNumber:
          type: string
        creditCardNumber:
          type: string
        creditId:
          type: integer
        amount:
          type: number
          format: double
        createDate:
          type: string
          format: date-time
        transactionType:
          type: string
    ApiResponse:
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: integer
        data:
          type: object
          additionalProperties: true
 